/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.org.ufpr.ees006.view;

import br.org.ufpr.ees006.foundation.Cliente;
import br.org.ufpr.ees006.DAO.ClienteDAO;
import br.org.ufpr.ees006.model.ModelClienteTable;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author Thiago Luis Garcia
 */
public class ViewCliente extends javax.swing.JDialog {

  
  private ModelClienteTable modelCliente;
  private int clickedLine = -1;

  public ViewCliente() {
    modelCliente = new ModelClienteTable();
    initComponents();
    listarCliente();
  }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    btNovo = new javax.swing.JButton();
    btAtualizar = new javax.swing.JButton();
    btExcluir = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    fieldCpf = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    fieldCodigo = new javax.swing.JTextField();
    fieldNome = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    fieldSobrenome = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    jScrollPane = new javax.swing.JScrollPane(tableCliente);
    tableCliente = new javax.swing.JTable();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Manter Cliente");
    setMaximumSize(new java.awt.Dimension(620, 408));
    setMinimumSize(new java.awt.Dimension(620, 408));
    setPreferredSize(new java.awt.Dimension(620, 408));
    setResizable(false);

    btNovo.setText("Novo");
    btNovo.setMaximumSize(new java.awt.Dimension(75, 25));
    btNovo.setMinimumSize(new java.awt.Dimension(75, 25));
    btNovo.setPreferredSize(new java.awt.Dimension(75, 25));
    btNovo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btNovoActionPerformed(evt);
      }
    });

    btAtualizar.setText("Atualizar");
    btAtualizar.setMaximumSize(new java.awt.Dimension(75, 25));
    btAtualizar.setMinimumSize(new java.awt.Dimension(75, 25));
    btAtualizar.setPreferredSize(new java.awt.Dimension(75, 25));
    btAtualizar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btAtualizarActionPerformed(evt);
      }
    });

    btExcluir.setText("Excluir");
    btExcluir.setMaximumSize(new java.awt.Dimension(75, 25));
    btExcluir.setMinimumSize(new java.awt.Dimension(75, 25));
    btExcluir.setPreferredSize(new java.awt.Dimension(75, 25));
    btExcluir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btExcluirActionPerformed(evt);
      }
    });

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    jLabel1.setText("Cliente");

    fieldCpf.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        fieldCpfActionPerformed(evt);
      }
    });

    jLabel3.setText("CPF:");

    jLabel2.setText("Código:");

    fieldCodigo.setEditable(false);
    fieldCodigo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        fieldCodigoActionPerformed(evt);
      }
    });

    fieldNome.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        fieldNomeActionPerformed(evt);
      }
    });

    jLabel4.setText("Nome:");

    fieldSobrenome.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        fieldSobrenomeActionPerformed(evt);
      }
    });

    jLabel5.setText("Sobrenome:");

    jScrollPane.setMinimumSize(new java.awt.Dimension(620, 369));
    jScrollPane.setPreferredSize(new java.awt.Dimension(620, 369));

    tableCliente.setModel(modelCliente);
    tableCliente.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
    tableCliente.setColumnSelectionAllowed(true);
    tableCliente.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tableClienteMouseClicked(evt);
      }
    });
    jScrollPane.setViewportView(tableCliente);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel1)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel2)
              .addComponent(jLabel3))
            .addGap(23, 23, 23)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addGroup(layout.createSequentialGroup()
                .addComponent(fieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
              .addGroup(layout.createSequentialGroup()
                .addComponent(fieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)))
            .addGap(23, 23, 23)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(fieldNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(fieldSobrenome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(13, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(fieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel4)
          .addComponent(fieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(6, 6, 6)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(fieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel5)
          .addComponent(fieldSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(btExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(btNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void fieldCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCodigoActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_fieldCodigoActionPerformed

  private void fieldCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCpfActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_fieldCpfActionPerformed

  private void fieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNomeActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_fieldNomeActionPerformed

  private void fieldSobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldSobrenomeActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_fieldSobrenomeActionPerformed

  private void tableClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableClienteMouseClicked

    clickedLine = tableCliente.rowAtPoint(evt.getPoint());

    Cliente cliente = modelCliente.getCliente(clickedLine);

    this.fieldCodigo.setText(String.valueOf(cliente.getId()));
    this.fieldCpf.setText(cliente.getCpf());
    this.fieldNome.setText(cliente.getNome());
    this.fieldSobrenome.setText(cliente.getSobrenome());
    
  }//GEN-LAST:event_tableClienteMouseClicked

  private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed

    Cliente cliente = new Cliente();
    ClienteDAO clienteDAO = new ClienteDAO();

    try {

      cliente.setId(clienteDAO.getMax());
      cliente.setCpf(fieldCpf.getText());
      cliente.setNome(fieldNome.getText());
      cliente.setSobrenome(fieldSobrenome.getText());

      clienteDAO.insert(cliente);

    } catch (Exception ex) {

      JOptionPane.showMessageDialog(null, "Erro ao inserir no banco de dados. E=" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);

    }

    listarCliente();
  }//GEN-LAST:event_btNovoActionPerformed

  private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed

    if (clickedLine != -1) {

      Cliente cliente = modelCliente.getCliente(clickedLine);

      cliente.setCpf(fieldCpf.getText());
      cliente.setNome(fieldNome.getText());
      cliente.setSobrenome(fieldSobrenome.getText());

      ClienteDAO dao = null;

      try {

        dao = new ClienteDAO();
        dao.update(cliente);

      } catch (Exception ex) {

        JOptionPane.showMessageDialog(null, "Erro ao atualizar no banco de dados.", "Erro", JOptionPane.ERROR_MESSAGE);

      }

      listarCliente();

    }
  }//GEN-LAST:event_btAtualizarActionPerformed

  private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed

    try {

      ClienteDAO dao = new ClienteDAO();

      int[] selectedRows = tableCliente.getSelectedRows();

      List<Cliente> toDelList = new ArrayList();

      for (int i = 0; i < selectedRows.length; i++) {

        Cliente cliente = modelCliente.getCliente(selectedRows[i]);
        dao.delete(cliente);
        toDelList.add(cliente);

      }

      listarCliente();

    } catch (Exception ex) {
      JOptionPane.showMessageDialog(null, "Erro ao realizar exclusão de Cliente", "Erro", JOptionPane.ERROR_MESSAGE);
    }
  }//GEN-LAST:event_btExcluirActionPerformed

  private void listarCliente() {

    try {

      ClienteDAO clienteDAO = new ClienteDAO();

      List<Cliente> listCliente;
      listCliente = clienteDAO.getList();
      modelCliente.setListClientes(listCliente);

    } catch (Exception ex) {

      JOptionPane.showMessageDialog(null, "Erro ao conectar com o banco de dados.", "Erro", JOptionPane.ERROR_MESSAGE);

    }

    clearScreen();

  }

  private void clearScreen() {

    this.fieldCodigo.setText("");
    this.fieldCpf.setText("");
    this.fieldNome.setText("");
    this.fieldSobrenome.setText("");

  }
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Windows".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new ViewCliente().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btAtualizar;
  private javax.swing.JButton btExcluir;
  private javax.swing.JButton btNovo;
  private javax.swing.JTextField fieldCodigo;
  private javax.swing.JTextField fieldCpf;
  private javax.swing.JTextField fieldNome;
  private javax.swing.JTextField fieldSobrenome;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JScrollPane jScrollPane;
  private javax.swing.JTable tableCliente;
  // End of variables declaration//GEN-END:variables
}
