package br.org.ufpr.ees006.view;

import br.org.ufpr.ees006.DAO.ItemDoPedidoDAO;
import br.org.ufpr.ees006.DAO.PedidoDAO;
import br.org.ufpr.ees006.foundation.Cliente;
import br.org.ufpr.ees006.foundation.ItemDoPedido;
import br.org.ufpr.ees006.foundation.Pedido;
import br.org.ufpr.ees006.model.ModelItemPedido;
import br.org.ufpr.ees006.model.ModelPedidoCliente;
import java.sql.SQLException;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author Thiago Luis Garcia
 */
public class ViewListarPedidoCliente extends javax.swing.JDialog {

  private ModelPedidoCliente modelPedidoCliente;
  private ModelItemPedido modelItemPedido;
  private int clickedPedido = -1;
  
  public ViewListarPedidoCliente() {
    modelPedidoCliente = new ModelPedidoCliente();
    modelItemPedido = new ModelItemPedido();
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    fieldCpf = new javax.swing.JTextField();
    btProcurar = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    tablePedido = new javax.swing.JTable();
    jScrollPane2 = new javax.swing.JScrollPane();
    tableItemPedido = new javax.swing.JTable();
    jLabel2 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Pedidos do Cliente");
    setMinimumSize(new java.awt.Dimension(620, 408));
    setResizable(false);

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    jLabel1.setText("Pedidos do Cliente");

    jLabel3.setText("CPF:");

    fieldCpf.setName(""); // NOI18N
    fieldCpf.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        fieldCpfActionPerformed(evt);
      }
    });

    btProcurar.setText("Procurar");
    btProcurar.setMaximumSize(new java.awt.Dimension(75, 25));
    btProcurar.setMinimumSize(new java.awt.Dimension(75, 25));
    btProcurar.setPreferredSize(new java.awt.Dimension(75, 25));
    btProcurar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btProcurarActionPerformed(evt);
      }
    });

    tablePedido.setModel(modelPedidoCliente);
    tablePedido.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tablePedidoMouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(tablePedido);

    tableItemPedido.setModel(modelItemPedido);
    jScrollPane2.setViewportView(tableItemPedido);

    jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    jLabel2.setText("Pedidos");

    jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    jLabel4.setText("Itens do Pedido");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addComponent(jScrollPane2)
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(23, 23, 23)
                .addComponent(fieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addComponent(jLabel1)
              .addComponent(jLabel2))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(btProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE))
        .addContainerGap(38, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(fieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btProcurar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel4)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(29, 29, 29))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProcurarActionPerformed

    try {

      PedidoDAO pedidoDAO = new PedidoDAO();

      List<Pedido> listPedido;
      listPedido = pedidoDAO.getList(fieldCpf.getText());
      modelPedidoCliente.setListPedidos(listPedido);

    } catch (Exception ex) {

      JOptionPane.showMessageDialog(null, "Erro ao conectar com o banco de dados.", "Erro", JOptionPane.ERROR_MESSAGE);

    }
    
  }//GEN-LAST:event_btProcurarActionPerformed

  private void fieldCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCpfActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_fieldCpfActionPerformed

  private void tablePedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePedidoMouseClicked
    
    if ( clickedPedido != -1 ) {
    
      clickedPedido = tablePedido.rowAtPoint(evt.getPoint());

      Pedido pedido = modelPedidoCliente.getPedido(clickedPedido);

      listarItens(pedido);
      
    }
    
  }//GEN-LAST:event_tablePedidoMouseClicked

  private void listarItens(Pedido pedido) {

    try {

      ItemDoPedidoDAO itemDAO = new ItemDoPedidoDAO();

      List<ItemDoPedido> listItem;
      listItem = itemDAO.getList(pedido.getId());
      modelItemPedido.setListItens(listItem);

    } catch (SQLException ex) {

      JOptionPane.showMessageDialog(null, "Erro ao conectar com o banco de dados.", "Erro", JOptionPane.ERROR_MESSAGE);

    }

  }
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Windows".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(ViewListarPedidoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(ViewListarPedidoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(ViewListarPedidoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(ViewListarPedidoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new ViewListarPedidoCliente().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btProcurar;
  private javax.swing.JTextField fieldCpf;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JTable tableItemPedido;
  private javax.swing.JTable tablePedido;
  // End of variables declaration//GEN-END:variables
}
