/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.org.ufpr.ees006.view;

import br.org.ufpr.ees006.DAO.ClienteDAO;
import br.org.ufpr.ees006.DAO.ItemDoPedidoDAO;
import br.org.ufpr.ees006.DAO.PedidoDAO;
import br.org.ufpr.ees006.DAO.ProdutoDAO;
import br.org.ufpr.ees006.foundation.Cliente;
import br.org.ufpr.ees006.foundation.ItemDoPedido;
import br.org.ufpr.ees006.foundation.Pedido;
import br.org.ufpr.ees006.foundation.Produto;
import br.org.ufpr.ees006.model.ModelItemPedido;
import br.org.ufpr.ees006.model.ModelProdutoTable;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author Thiago Luis Garcia
 */
public class ViewPedidoCliente extends javax.swing.JFrame {
  
  private ModelProdutoTable modelProduto;
  private ModelItemPedido modelItemPedido;
  private int clickedLineProduto = -1;
  private int clickedLineItem = -1;

  /**
   * Creates new form ViewPedidoCliente
   */
  public ViewPedidoCliente() {
    modelProduto = new ModelProdutoTable();
    modelItemPedido = new ModelItemPedido();
    initComponents();
    listarProduto();
  }
  
  private void listarProduto() {

    try {

      ProdutoDAO produtoDAO = new ProdutoDAO();

      List<Produto> listProduto;
      listProduto = produtoDAO.getList();
      modelProduto.setListProdutos(listProduto);

    } catch (Exception ex) {

      JOptionPane.showMessageDialog(null, "Erro ao conectar com o banco de dados.", "Erro", JOptionPane.ERROR_MESSAGE);

    }

  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    fieldCpf = new javax.swing.JTextField();
    jScrollPane1 = new javax.swing.JScrollPane();
    tableProduto = new javax.swing.JTable();
    jLabel2 = new javax.swing.JLabel();
    jScrollPane2 = new javax.swing.JScrollPane();
    tableItens = new javax.swing.JTable();
    jLabel4 = new javax.swing.JLabel();
    btAdicionar = new javax.swing.JButton();
    btRemover = new javax.swing.JButton();
    btGravar = new javax.swing.JButton();
    btSomar = new javax.swing.JButton();
    btSubtrair = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Manter Pedido");
    setMinimumSize(new java.awt.Dimension(620, 408));
    setResizable(false);

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    jLabel1.setText("Pedido");

    jLabel3.setText("CPF:");

    fieldCpf.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        fieldCpfActionPerformed(evt);
      }
    });

    tableProduto.setModel(modelProduto);
    tableProduto.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tableProdutoMouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(tableProduto);

    jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    jLabel2.setText("Lista de Produtos");

    tableItens.setModel(modelItemPedido);
    tableItens.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tableItensMouseClicked(evt);
      }
    });
    jScrollPane2.setViewportView(tableItens);

    jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    jLabel4.setText("Produtos do Pedido");

    btAdicionar.setText("Adicionar");
    btAdicionar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btAdicionarActionPerformed(evt);
      }
    });

    btRemover.setText("Remover");
    btRemover.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btRemoverActionPerformed(evt);
      }
    });

    btGravar.setText("Gravar");
    btGravar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btGravarActionPerformed(evt);
      }
    });

    btSomar.setText("+");
    btSomar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btSomarActionPerformed(evt);
      }
    });

    btSubtrair.setText("-");
    btSubtrair.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btSubtrairActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addContainerGap(578, Short.MAX_VALUE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(23, 23, 23)
                .addComponent(fieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel2)
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                      .addComponent(btAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                      .addComponent(btRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel4)
                    .addGap(87, 87, 87)
                    .addComponent(btSomar)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btSubtrair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                  .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
            .addGap(23, 23, 23))))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btGravar)
        .addGap(23, 23, 23))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel3)
              .addComponent(fieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(20, 20, 20)
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addGap(74, 74, 74)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jLabel4)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btSubtrair)
                .addComponent(btSomar)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btGravar))
              .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(btAdicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRemover)))))
        .addContainerGap(18, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void fieldCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCpfActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_fieldCpfActionPerformed

  private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
    
    if ( clickedLineProduto != -1 ) {
      
      ItemDoPedido item = new ItemDoPedido(modelProduto.getProduto(clickedLineProduto), 1);
      modelItemPedido.setValue(item);
      
    }
  }//GEN-LAST:event_btAdicionarActionPerformed

  private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
    
    if ( clickedLineItem != -1 ) {
      modelItemPedido.delete(clickedLineItem);
    }
    
  }//GEN-LAST:event_btRemoverActionPerformed

  private void tableProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProdutoMouseClicked
    clickedLineProduto = tableProduto.rowAtPoint(evt.getPoint());
  }//GEN-LAST:event_tableProdutoMouseClicked

  private void tableItensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableItensMouseClicked
    clickedLineItem = tableItens.rowAtPoint(evt.getPoint());
  }//GEN-LAST:event_tableItensMouseClicked

  private void btSomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSomarActionPerformed
    
    if ( clickedLineItem != -1 ) {
      
      ItemDoPedido item;
      item = modelItemPedido.getItem(clickedLineItem);
      int quantidade = item.getQtdade();
      quantidade++;
      item.setQtdade(quantidade);
      modelItemPedido.setValueAt(item, clickedLineItem, 1);
      clickedLineItem = -1;
      
    }
    
  }//GEN-LAST:event_btSomarActionPerformed

  private void btSubtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubtrairActionPerformed
    
    if ( clickedLineItem != -1 ) {
      
      ItemDoPedido item;
      item = modelItemPedido.getItem(clickedLineItem);
      int quantidade = item.getQtdade();
      quantidade--;
      if (quantidade <= 0 ) {
        modelItemPedido.delete(clickedLineItem);
      } else {
        item.setQtdade(quantidade);
        modelItemPedido.setValueAt(item, clickedLineItem, 1);
      }
      clickedLineItem = -1;
      
    }
    
  }//GEN-LAST:event_btSubtrairActionPerformed

  private void btGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarActionPerformed

    Date date = new Date();
    ClienteDAO clienteDAO = new ClienteDAO();
    Cliente cliente;
    Pedido pedido = new Pedido();
    PedidoDAO pedidoDAO = new PedidoDAO();
    List<ItemDoPedido> itens;
    
    try {
      
      cliente = clienteDAO.getCliente(fieldCpf.getText());

      pedido.setId(pedidoDAO.getMax());
      pedido.setCliente(cliente);
      pedido.setData(date);
      
      pedidoDAO.insert(pedido);
            
      itens = modelItemPedido.getItens();

      for (int i = 0; i < itens.size(); i++) {

        ItemDoPedido item = modelItemPedido.getItem(i);
        ItemDoPedidoDAO itemDAO = new ItemDoPedidoDAO();
        itemDAO.insert(pedido, item);
        this.modelItemPedido.delete(i);
        
      }
      
      JOptionPane.showMessageDialog(null, "Pedido " + pedido.getId() + " criado com sucesso.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
      this.fieldCpf.setText("");

    } catch (Exception ex) {

      JOptionPane.showMessageDialog(null, "Erro ao inserir no banco de dados. E=" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);

    }
    
  }//GEN-LAST:event_btGravarActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Windows".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(ViewPedidoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(ViewPedidoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(ViewPedidoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(ViewPedidoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new ViewPedidoCliente().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btAdicionar;
  private javax.swing.JButton btGravar;
  private javax.swing.JButton btRemover;
  private javax.swing.JButton btSomar;
  private javax.swing.JButton btSubtrair;
  private javax.swing.JTextField fieldCpf;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JTable tableItens;
  private javax.swing.JTable tableProduto;
  // End of variables declaration//GEN-END:variables
}
